from enum import Enum


# Enum for CTAs
class CTAs(Enum):
    BIOTECHNOLOGY = "Biotechnology"
    QUANTUM_SCIENCE = "Quantum Science"
    FUTURE_GEN_WI_TECH = "Future Generation Wireless Technology"
    ADV_MATERIALS = "Advanced Materials"
    TRUSTED_AI = "Trusted AI and Autonomy"
    INTEGRATED_NETWORK_SYS_SYS = "Integrated Network Systems-of-Systems"
    MICROELECTRONICS = "Microelectronics"
    SPACE_TECHNOLOGY = "Space Technology"
    RENEWABLE_ENERGY = "Renewable Energy Generation and Storage"
    ADV_COMPUTING_SOFTWARE = "Advanced Computing and Software"
    HUMAN_MACHINE_INTERFACES = "Human-Machine Interfaces"
    DIRECTED_ENERGY = "Directed Energy"
    HYPERSONICS = "Hypersonics"
    INTEGRATED_SENSING_CYBER = "Integrated Sensing and Cyber"
    OSINT_ISR = "OSINT ISR"


# Used to map sub CTAs to CTAs
SUBCTA_TO_CTA = {
    "Synthetic Biology": CTAs.BIOTECHNOLOGY.value,
    "Human Performance Enhancement": CTAs.BIOTECHNOLOGY.value,
    "Regenerative Medicine": CTAs.BIOTECHNOLOGY.value,
    "Environmental Biotechnology": CTAs.BIOTECHNOLOGY.value,
    "Biomaterials & Bioelectronics": CTAs.BIOTECHNOLOGY.value,
    "Neurotechnology & Brain-Computer Interfaces": CTAs.BIOTECHNOLOGY.value,
    "Quantum Computing": CTAs.QUANTUM_SCIENCE.value,
    "Quantum Sensing": CTAs.QUANTUM_SCIENCE.value,
    "Quantum Communication": CTAs.QUANTUM_SCIENCE.value,
    "Quantum Radar & Imaging": CTAs.QUANTUM_SCIENCE.value,
    "Quantum Metrology": CTAs.QUANTUM_SCIENCE.value,
    "Quantum Materials": CTAs.QUANTUM_SCIENCE.value,
    "Quantum AI": CTAs.QUANTUM_SCIENCE.value,
    "5G & Beyond Networks": CTAs.FUTURE_GEN_WI_TECH.value,
    "mmWave Technology": CTAs.FUTURE_GEN_WI_TECH.value,
    "Massive MIMO": CTAs.FUTURE_GEN_WI_TECH.value,
    "Mesh Networking": CTAs.FUTURE_GEN_WI_TECH.value,
    "Spectrum Sharing & Cognitive Radio": CTAs.FUTURE_GEN_WI_TECH.value,
    "Quantum Wireless Communications": CTAs.FUTURE_GEN_WI_TECH.value,
    "THz Technology": CTAs.FUTURE_GEN_WI_TECH.value,
    "Nanomaterials": CTAs.ADV_MATERIALS.value,
    "Metamaterials": CTAs.ADV_MATERIALS.value,
    "Smart Materials": CTAs.ADV_MATERIALS.value,
    "Advanced Ceramics & Composites": CTAs.ADV_MATERIALS.value,
    "Bio-Inspired Materials": CTAs.ADV_MATERIALS.value,
    "Graphene & 2D Materials": CTAs.ADV_MATERIALS.value,
    "High-Entropy Alloys": CTAs.ADV_MATERIALS.value,
    "Explainable AI (XAI)": CTAs.TRUSTED_AI.value,
    "Autonomous Unmanned Vehicles & Systems": CTAs.TRUSTED_AI.value,
    "Swarm Intelligence": CTAs.TRUSTED_AI.value,
    "Cyber Defense AI": CTAs.TRUSTED_AI.value,
    "Autonomous Weapons Systems": CTAs.TRUSTED_AI.value,
    "Command & Control AI": CTAs.TRUSTED_AI.value,
    "Multi-Domain Command and Control (MDC2)": CTAs.INTEGRATED_NETWORK_SYS_SYS.value,
    "Interoperability Standards and Protocols": CTAs.INTEGRATED_NETWORK_SYS_SYS.value,
    "Tactical Edge Networking": CTAs.INTEGRATED_NETWORK_SYS_SYS.value,
    "Cyber-Physical Systems (CPS)": CTAs.INTEGRATED_NETWORK_SYS_SYS.value,
    "Joint All-Domain Command and Control (JADC2)": CTAs.INTEGRATED_NETWORK_SYS_SYS.value,
    "Resilient Network Architectures": CTAs.INTEGRATED_NETWORK_SYS_SYS.value,
    "Edge Computing and Distributed Systems": CTAs.INTEGRATED_NETWORK_SYS_SYS.value,
    "Radiation-Hardened Electronics": CTAs.MICROELECTRONICS.value,
    "Trusted Microelectronics": CTAs.MICROELECTRONICS.value,
    "Chip-Scale Atomic Clocks (CSACs)": CTAs.MICROELECTRONICS.value,
    "Advanced Packaging & Integration": CTAs.MICROELECTRONICS.value,
    "Heterogeneous Integration": CTAs.MICROELECTRONICS.value,
    "Ultra-Low Power Electronics": CTAs.MICROELECTRONICS.value,
    "Quantum Microelectronics": CTAs.MICROELECTRONICS.value,
    "SATCOM": CTAs.SPACE_TECHNOLOGY.value,
    "Space-Based ISR": CTAs.SPACE_TECHNOLOGY.value,
    "Space Situational Awareness (SSA)": CTAs.SPACE_TECHNOLOGY.value,
    "Launch Systems & Propulsion": CTAs.SPACE_TECHNOLOGY.value,
    "Space-Based Positioning, Navigation & Timing (PNT)": CTAs.SPACE_TECHNOLOGY.value,
    "Counterspace, Awareness & Defense": CTAs.SPACE_TECHNOLOGY.value,
    "In-Space Manufacturing & Repair": CTAs.SPACE_TECHNOLOGY.value,
    "Solar Power": CTAs.RENEWABLE_ENERGY.value,
    "Energy Harvesting": CTAs.RENEWABLE_ENERGY.value,
    "Microgrids": CTAs.RENEWABLE_ENERGY.value,
    "Advanced Battery Technologies": CTAs.RENEWABLE_ENERGY.value,
    "Hydrogen Fuel Cells": CTAs.RENEWABLE_ENERGY.value,
    "Waste-to-Energy Technologies": CTAs.RENEWABLE_ENERGY.value,
    "Energy Storage & Distribution Systems": CTAs.RENEWABLE_ENERGY.value,
    "High-Performance Computing (HPC)": CTAs.ADV_COMPUTING_SOFTWARE.value,
    "AI & Machine Learning": CTAs.TRUSTED_AI.value,
    "Quantum Computing": CTAs.ADV_COMPUTING_SOFTWARE.value,
    "Edge Computing": CTAs.ADV_COMPUTING_SOFTWARE.value,
    "Cyber Defense & Zero-Trust": CTAs.ADV_COMPUTING_SOFTWARE.value,
    "Software-Defined Networking (SDN)": CTAs.ADV_COMPUTING_SOFTWARE.value,
    "Cloud Computing & Data Management": CTAs.ADV_COMPUTING_SOFTWARE.value,
    "Wearable Interfaces": CTAs.HUMAN_MACHINE_INTERFACES.value,
    "Brain Computer Interfaces (BCI)": CTAs.HUMAN_MACHINE_INTERFACES.value,
    "Voice-Activated Systems": CTAs.HUMAN_MACHINE_INTERFACES.value,
    "Gesture-Based Systems": CTAs.HUMAN_MACHINE_INTERFACES.value,
    "Tactile & Haptic Feedback Systems": CTAs.HUMAN_MACHINE_INTERFACES.value,
    "Exoskeletons & Powered Wearables": CTAs.HUMAN_MACHINE_INTERFACES.value,
    "Multi-Modal Interfaces": CTAs.HUMAN_MACHINE_INTERFACES.value,
    "High-Power Microwave Systems ": CTAs.DIRECTED_ENERGY.value,
    "Targeting and control systems": CTAs.DIRECTED_ENERGY.value,
    "Laser Technologies": CTAs.DIRECTED_ENERGY.value,
    "High-Energy Laser Weapons (HPL)": CTAs.DIRECTED_ENERGY.value,
    "High-Power Microwave Weapons (HPM)": CTAs.DIRECTED_ENERGY.value,
    "Particle Beam Weapons": CTAs.DIRECTED_ENERGY.value,
    "Non-Lethal Directed Energy Weapons": CTAs.DIRECTED_ENERGY.value,
    "Counter-UAS (cUAS)": CTAs.DIRECTED_ENERGY.value,
    "Directed Energy for Missile Defense": CTAs.DIRECTED_ENERGY.value,
    "Electronic Warfare w/ DE": CTAs.DIRECTED_ENERGY.value,
    "Defense": CTAs.HYPERSONICS.value,
    "Aircraft": CTAs.HYPERSONICS.value,
    "Systems": CTAs.HYPERSONICS.value,
    "Hypersonic Glide Vehicles": CTAs.HYPERSONICS.value,
    "Hypersonic Cruise Missiles": CTAs.HYPERSONICS.value,
    "Advanced Propulsion Systems": CTAs.HYPERSONICS.value,
    "Thermal Protection Systems": CTAs.HYPERSONICS.value,
    "Aerodynamics & Flight Control": CTAs.HYPERSONICS.value,
    "Advanced Materials & Structures": CTAs.HYPERSONICS.value,
    "Counter-Hypersonic Defense Systems": CTAs.HYPERSONICS.value,
    "Cybersecurity": CTAs.INTEGRATED_SENSING_CYBER.value,
    "Electronic Warfare": CTAs.INTEGRATED_SENSING_CYBER.value,
    "Radar": CTAs.INTEGRATED_SENSING_CYBER.value,
    "Communications": CTAs.INTEGRATED_SENSING_CYBER.value,
    "Wideband Sensing": CTAs.INTEGRATED_SENSING_CYBER.value,
    "Multi Intelligence (Multi-INT) Fusion": CTAs.INTEGRATED_SENSING_CYBER.value,
    "Cyber-Electromagnetic Activities (CEMA)": CTAs.INTEGRATED_SENSING_CYBER.value,
    "Cybersecurity of Sensing Systems": CTAs.INTEGRATED_SENSING_CYBER.value,
    "Cyber-Physical System (CPS) Defense": CTAs.INTEGRATED_SENSING_CYBER.value,
    "Advanced SIGINT": CTAs.INTEGRATED_SENSING_CYBER.value,
    "AI-Driven Cyber Defense": CTAs.INTEGRATED_SENSING_CYBER.value,
    "Integrated ISR": CTAs.INTEGRATED_SENSING_CYBER.value,
    "Advanced GEOINT": CTAs.INTEGRATED_SENSING_CYBER.value,
    "Sensor Management Software": CTAs.INTEGRATED_SENSING_CYBER.value,
    "Hyper- & Multi-Spectral Sensors": CTAs.INTEGRATED_SENSING_CYBER.value,
    "LiDAR & Ground-Penetrating Radar Sensors": CTAs.INTEGRATED_SENSING_CYBER.value,
    "Acoustic Sensors": CTAs.INTEGRATED_SENSING_CYBER.value,
    "Radio Frequency (RF) Sensors": CTAs.INTEGRATED_SENSING_CYBER.value,
    "Web & Social Media Monitoring": CTAs.OSINT_ISR.value,
    "Open-Source GEOINT": CTAs.OSINT_ISR.value,
    "Web Scraping & Aggregators": CTAs.OSINT_ISR.value,
    "Metadata, Text & Document Analysis": CTAs.OSINT_ISR.value,
    "Multimedia Analysis": CTAs.OSINT_ISR.value,
    "Predictive & Pattern Recognition AI": CTAs.OSINT_ISR.value,
    "Relationship Mapping & Network Analysis": CTAs.OSINT_ISR.value,
    "Cyber Threat Intelligence & Dark Web Monitoring": CTAs.OSINT_ISR.value,
    "Real-Time Monitoring": CTAs.OSINT_ISR.value,
    "Big Data Analytics": CTAs.OSINT_ISR.value,
}
